[package]
name = "read_bruker_data"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "read_bruker_data"
path = "src/main.rs"

[dependencies]
timsrust = "0.4.2"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = "2.0"
rayon = "1.8"
chrono = "0.4"